[versions]
compileSdk = "37"
minSdk = "26"
targetSdk = "37"

activityCompose = "1.13.0"
lifecycle = "2.11.0"
composeBom = "2026.09.00"
navigation = "2.10.2"
kotlin = "2.2.10"
kotlinxSerialization = "1.9.0"
kotlinxCoroutines = "1.11.0"
exifInterface = "1.4.2"
mlkitTextRecognition = "16.0.1"
mlkitTextRecognitionDevanagari = "16.0.1"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifInterface" }
mlkit-text-recognition = { module = "com.google.mlkit:text-recognition", version.ref = "mlkitTextRecognition" }
mlkit-text-recognition-devanagari = { module = "com.google.mlkit:text-recognition-devanagari", version.ref = "mlkitTextRecognitionDevanagari" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }

[bundles]
compose = [
    "compose-ui",
    "compose-ui-tooling-preview",
    "compose-material3"
]
